#file: noinspection UndefinedParamsPresent
name: Build and deploy to Azure App Service

env:
  AZURE_WEBAPP_NAME: tomboonedotcom
  PYTHON_VERSION: '3.13'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install poetry-plugin-export
        run: poetry self add poetry-plugin-export

      - name: Export dependencies to requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
